### ISSUE TITLE
Possible Memory leak

### ISSUE THREAD

**Issue by kingp0dd** [kpetremann/mqtt-exporter#99]
i realized this just now when looking at grafana graphs

[//

![Image](https://github.com/user-attachments/assets/e6c5b801-411d-4f27-af1c-81baeb1a339f)

](url)

```

mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682174_cpu', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682174_cpu_average', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682174_mem', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682175_cpu', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682175_cpu_average', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682175_mem', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682177_cpu', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682177_cpu_average', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682177_mem', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682178_cpu', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682178_cpu_average', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682178_mem', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682180_cpu', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682180_cpu_average', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682180_mem', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682181_cpu', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682181_cpu_average', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682181_mem', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682183_cpu', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682183_cpu_average', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682183_mem', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682191_cpu', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682191_cpu_average', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682191_mem', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682193_cpu', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682193_cpu_average', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682193_mem', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682194_cpu', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682194_cpu_average', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682194_mem', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682205_cpu', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682205_cpu_average', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682205_mem', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682207_cpu', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682207_cpu_average', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682207_mem', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682209_cpu', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682209_cpu_average', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682209_mem', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682210_cpu', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682210_cpu_average', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682210_mem', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682212_cpu', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682212_cpu_average', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682212_mem', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682217_cpu', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682217_cpu_average', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682217_mem', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682222_cpu', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682222_cpu_average', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682222_mem', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682223_cpu', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682223_cpu_average', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682223_mem', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682225_cpu', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682225_cpu_average', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682225_mem', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682228_cpu', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682228_cpu_average', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682228_mem', labels=())
mqtt-exporter  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqttexporter_cpu_usages_1682230_cpu', labels=())
```

**Comment by kpetremann** [comment]
Hi @kingp0dd,

Which version do you use? I've fixed a memory leak recently: #97

But here, it looks like the exporter is creating metrics for events you might not want. If so, I would suggest to use MQTT_IGNORED_TOPICS.
The exporter aims to be generic and to transform all events into a metric (especially thought for IOT sensors), so a very busy MQTT queue, means a lot of metrics hence a lot of memory.

Let me know if I am missing something.

**Comment by 29821632** [comment]
Hi there. First-time user of this exporter and noticed that by default it enumerates thousands of metrics, similar to above, but for devices/vendors that shouldn't be present in my dedicated zigbee2mqtt mosquitto instance. On startup I get thousands of lines similar to this printed to stdout
```
mqtt-exporter-mqtt-exporter-1  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqtt_clusters_hvacPumpCfgCtrl_attributes_power_ID', labels=())
mqtt-exporter-mqtt-exporter-1  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqtt_clusters_hvacPumpCfgCtrl_attributes_power_type', labels=())
mqtt-exporter-mqtt-exporter-1  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqtt_clusters_hvacPumpCfgCtrl_attributes_pumpStatus_ID', labels=())
mqtt-exporter-mqtt-exporter-1  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqtt_clusters_hvacPumpCfgCtrl_attributes_pumpStatus_type', labels=())
mqtt-exporter-mqtt-exporter-1  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqtt_clusters_hvacPumpCfgCtrl_attributes_speed_ID', labels=())
mqtt-exporter-mqtt-exporter-1  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqtt_clusters_hvacPumpCfgCtrl_attributes_speed_type', labels=())
mqtt-exporter-mqtt-exporter-1  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqtt_clusters_hvacThermostat_ID', labels=())
mqtt-exporter-mqtt-exporter-1  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqtt_clusters_hvacThermostat_attributes_SinopeAuxCycleOutput_ID', labels=())
mqtt-exporter-mqtt-exporter-1  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqtt_clusters_hvacThermostat_attributes_SinopeAuxCycleOutput_manufacturerCode', labels=())
mqtt-exporter-mqtt-exporter-1  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqtt_clusters_hvacThermostat_attributes_SinopeAuxCycleOutput_type', labels=())
mqtt-exporter-mqtt-exporter-1  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqtt_clusters_hvacThermostat_attributes_SinopeBacklight_ID', labels=())
mqtt-exporter-mqtt-exporter-1  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqtt_clusters_hvacThermostat_attributes_SinopeBacklight_manufacturerCode', labels=())
mqtt-exporter-mqtt-exporter-1  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqtt_clusters_hvacThermostat_attributes_SinopeBacklight_type', labels=())
mqtt-exporter-mqtt-exporter-1  | INFO:mqtt-exporter:creating prometheus metric: PromMetricId(name='mqtt_clusters_hvacThermostat_attributes_SinopeMainCycleOutput_ID', labels=())
```

I'm using a simple docker-compose for `mqtt-exporter` and it hits zigbee2mqtt's mosquitto container on localhost...
```
services:
  mqtt-exporter:
    image: kpetrem/mqtt-exporter
    ports:
      - 9000:9000
    environment:
      - MQTT_ADDRESS=127.0.0.1
```

Docker image: `kpetrem/mqtt-exporter   latest    294118990de0   6 days ago     51.8MB`

I only have 5 zigbee temp sensors but the exporter exposes 15000 metrics...
```
$ curl -s 127.0.0.1:9000/metrics | wc -l
15071
```

Let me know if you need further info but an explosion of metrics being exported could be a cause of a memory leak.

**Comment by kpetremann** [comment]
hi @29821632,

This exporter is generic: each successfully parsed message in MQTT is converted to at least one metric (more if it is a JSON).

Zigbee2mqtt itself sends a lot of message regarding its configuration and the configuration of the zigbee stick.
To give you an idea, without filtering, I have 6k metrics for about 15 IOT devices, and it takes 54.7MB in RAM.

You can, as stated in https://github.com/kpetremann/mqtt-exporter?tab=readme-ov-file#configuration:
- use `MQTT_TOPIC` option to subscribe to a more precise topic path
- filter out using `MQTT_IGNORED_TOPICS`

The logs you have, is just the messages that the exporter finds when connecting to MQTT.
You can reduce the log level with `LOG_LEVEL`.

If you need more precise filtering, you can also use a Prometheus recording rule, or use another exporter like https://github.com/hikhvar/mqtt2prometheus.

> an explosion of metrics being exported could be a cause of a memory leak

As I said in my previous response in this issue, the more you have different message in the MQTT, the more you have metrics.

**Comment by kingp0dd** [comment]
> Hi [@kingp0dd](https://github.com/kingp0dd),
> 
> Which version do you use? I've fixed a memory leak recently: [#97](https://github.com/kpetremann/mqtt-exporter/pull/97)
> 
> But here, it looks like the exporter is creating metrics for events you might not want. If so, I would suggest to use MQTT_IGNORED_TOPICS. The exporter aims to be generic and to transform all events into a metric (especially thought for IOT sensors), so a very busy MQTT queue, means a lot of metrics hence a lot of memory.
> 
> Let me know if I am missing something.

I was using the v1.7.0 when i encountered this.
I tried your suggestion but my MQTT is publishing multiple topics and might increase in the future:

![Image](https://github.com/user-attachments/assets/34fba3a3-7031-46de-aeef-ccd34f86ae5f)

so I tried this option:

MQTT_TOPIC=deye

However, when I do that, I get no metrics. If I use default (all topics), I get the payload I want:

```
mqttexporter_message_created{topic="deye_day_energy"} 1.7427004083549366e+09
mqttexporter_message_created{topic="deye_total_energy"} 1.7427004083557084e+09
mqttexporter_message_created{topic="deye_ac"} 1.7427004083564131e+09
mqttexporter_message_created{topic="deye_uptime"} 1.7427004083599563e+09
mqttexporter_message_created{topic="deye_dc"} 1.7427004083600576e+09
mqttexporter_message_created{topic="deye_operating_power"} 1.7427004083622098e+09
mqttexporter_message_created{topic="deye_radiator_temp"} 1.7427004083644514e+09
mqttexporter_message_created{topic="deye_igbt_temp"} 1.7427004083648782e+09

```

**Comment by kingp0dd** [comment]
I found the answer here:
```
https://github.com/hikhvar/mqtt2prometheus
temperature{sensor="livingroom",topic="devices/home/livingroom"} 23.2
heat_index{sensor="livingroom",topic="devices/home/livingroom"} 22.92
humidity{sensor="livingroom",topic="devices/home/livingroom"} 51.6
The label sensor is extracted with the default device_id_regex (.*/)?(?P<deviceid>.*) from the MQTT topic devices/home/livingroom. The device_id_regex is able to extract exactly one label from the topic path. It extracts only the deviceid regex capture group into the sensor prometheus label. To extract more labels from the topic path, have a look at [this FAQ answer](https://github.com/hikhvar/mqtt2prometheus#extract-more-labels-from-the-topic-path).

The topic path can contain multiple wildcards. MQTT has two wildcards:

+: Single level of hierarchy in the topic path
#: Many levels of hierarchy in the topic path
This [page](https://mosquitto.org/man/mqtt-7.html) explains the wildcard in depth.

For example the topic_path: devices/+/sensors/# will match:

devices/home/sensors/foo/bar
devices/workshop/sensors/temperature
```

My fault, didn't know syntax for MQTT.

I'll observe again if I will still get high RAM after filtering.

**Comment by kpetremann** [comment]
hi,

> doing deye/# now works, but I noticed that the third-level subtopics are being combined

According #69, "deye" is  working well when setting ` KEEP_FULL_TOPIC=True`.
Does it help?
